// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDIjy9Pg6yprUsZKDUtwd63LZU95ZDhvw',
    appId: '1:1007469700131:web:4a94e021effca7c3607d96',
    messagingSenderId: '1007469700131',
    projectId: 'cungacash',
    authDomain: 'cungacash.firebaseapp.com',
    storageBucket: 'cungacash.firebasestorage.app',
    measurementId: 'G-Z1DZS7LZ9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd91CRnenydlh3PXKs5zP9JAfnVshtDuc',
    appId: '1:1007469700131:android:672797d90d9870c8607d96',
    messagingSenderId: '1007469700131',
    projectId: 'cungacash',
    storageBucket: 'cungacash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvKUsfUs7evdZl5StJmUEQWeQDu9ZVy4c',
    appId: '1:1007469700131:ios:d30f1f223ec28cd6607d96',
    messagingSenderId: '1007469700131',
    projectId: 'cungacash',
    storageBucket: 'cungacash.firebasestorage.app',
    iosBundleId: 'com.example.cungacash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvKUsfUs7evdZl5StJmUEQWeQDu9ZVy4c',
    appId: '1:1007469700131:ios:176a90f2bab9a36d607d96',
    messagingSenderId: '1007469700131',
    projectId: 'cungacash',
    storageBucket: 'cungacash.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDIjy9Pg6yprUsZKDUtwd63LZU95ZDhvw',
    appId: '1:1007469700131:web:30b3a3224ff3934e607d96',
    messagingSenderId: '1007469700131',
    projectId: 'cungacash',
    authDomain: 'cungacash.firebaseapp.com',
    storageBucket: 'cungacash.firebasestorage.app',
    measurementId: 'G-NG91YN5ZQY',
  );
}
